set -g mouse on

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-a
unbind C-b

bind v split-window -h
bind s split-window -v
unbind %
unbind '"'


bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r H resize-pane -L 5

bind -r m resize-pane -Z

bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key h select-pane -L

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

set-option -g allow-rename off
set-option -g automatic-rename off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"


run '~/.tmux/plugins/tpm/tpm'
